export interface Question{
  id: Number,
  q_title: String,
  q_answer_type: Number,
  q_answers?: String[],
  q_helptext: String,
  q_points: Number,
  q_created?: Date,
  q_edited?: Date,
  q_createdby?: String,
  q_answered: Boolean,
  q_poolId: Number,
}

export interface QuestionPool{
  poolId: Number,
  poolURIName: String,
  poolName: String,
  poolQuestions: Number,
}

export const questionPools: QuestionPool[] = [
  {
    poolId: 1,
    poolURIName: "LPIC-01",
    poolName: "Linux Professional Institute Certification, Stage 1",
    poolQuestions: 12,
  },
];


export const questions: Question[] = [
  {
  id: 1,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 1,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 2,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 2,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 3,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 3,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 4,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 3,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 5,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 2,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 6,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 1,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 7,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 2,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 8,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 3,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 9,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 1,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 10,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 2,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 10,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 3,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 11,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 2,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
{
  id: 12,
  q_title: "Wie lautet die Hauptstadt von NRW?",
  q_answer_type: 1,
  q_helptext: "NRW liegt als Bundesland im Westen von Deutschland. Bayern z.b. im Süden.",
  q_points: 3,
  q_createdby: "b.aranda@outlook.de",
  q_answered: false,
  q_poolId: 1,
},
];
